compat-tool/README.md, compat-tool/compat/compat.py
Modified code to support passing single file (existing functionality) or a directory name (containing one or more log files)
=> adding support for directory of log files

compat-tool/compat/compat.py
*Issue # , if available:*[#19](https://github.com/awslabs/amazon-documentdb-tools/issues/19)
*Description of changes: Converted usage of `yaml.load()` to safer `yaml.safe_load()`
=> Update to use yaml.safe_load()

index-tool/migrationtools/documentdb_index_tool.py
=> fixed issue when collection has no indexes (capped collections)

monitoring/docdb-dashboarder/README.md, monitoring/docdb-dashboarder/create-docdb-dashboard.py, monitoring/docdb-dashboarder/widgets.py
=> Adding DocDB Dashboarder

global-clusters-automation/README.md, global-clusters-automation/add_secondarycluster.py
Remove hardcoded DocumentDB version.
=> user specified DocumentDB version

compat-tool/README.md, compat-tool/compat.py
*Issue 61
- Updated README
- Small updates to arguments help and output.
=> Updated README for compatibility tool

monitoring/docdb-stat/README.md, monitoring/docdb-stat/docdbstat.py
Real-time Amazon DocumentDB server stats monitoring tool
=> Add docdbstat tool

performance/index-cardinality-detection/detect-cardinality.py, performance/index-cardinality-detection/requirements.txt
fixing issues with compound indexes not reporting
=> adding support for compound index cardinality

monitoring/docdb-stat/docdbstat.py
*Issue #88 
- Calculate opcounters as a rate / polling_interval
- Add description to each function
=> Update docdb-stat tool to output opcounters as a rate per polling interval

mvu-tool/README.md, mvu-tool/mvu-cdc-migrator.py
=> Adding MVU CDC Migrator

index-tool/migrationtools/documentdb_index_tool.py
No issue filed at this time.
adding system.users.metadata.json to list of skipped files so it would not be processed by the scripts
=> feat: adding system.users.metadata.json to list of skipped files

global-clusters-automation/failover_and_delete_global_cluster.py
*Issue # 99, if available:*
Modified the delete_global_cluster function to check for promotion of all secondary clusters to standalone clusters and delete them after promotion
=> Fixed issue99

compat-tool/README.md, compat-tool/compat.py
*Issue #, if available:* Issue # 72
Added option to excluded directories separated by comma to skip directories if needed when using compatibility tool
=> added option to exclude directories when using compatibility tool

performance/compression-review/README.md, performance/compression-review/compression-review.py
added support for dictionaries, zstandard, and zlib
=> added support for dictionaries, zstandard, and zlib

migration/data-differ/data-differ.py
=> Fix missed case changes in data-differ.py

monitoring/docdb-dashboarder/create-docdb-dashboard.py, monitoring/docdb-dashboarder/widgets.py
=> simplify config file for maintainability

monitoring/docdb-dashboarder/README.md, monitoring/docdb-dashboarder/create-docdb-dashboard.py, monitoring/docdb-dashboarder/widgets.py
Updated to monitor metrics from migrator and DMS. updated the README with required parameters
=> Dashboarder cdc full load and DMS

performance/README.md, performance/metric-analyzer/README.md, performance/metric-analyzer/context/buffer_cache_low.html, performance/metric-analyzer/context/connection_limit.html, performance/metric-analyzer/context/cpu_overutilized.html, performance/metric-analyzer/context/cpu_underutilized.html, performance/metric-analyzer/context/graviton_upgrade.html, performance/metric-analyzer/context/index_cache_low.html, performance/metric-analyzer/context/read_preference.html, performance/metric-analyzer/context/remove_instances.html, performance/metric-analyzer/context/single_az.html, performance/metric-analyzer/metric-analyzer.py, performance/metric-analyzer/requirements.txt
Initial check-in for Metric Analyzer. This tool analyzes the output of the Metric Collector Tool to provide recommendations for optimizing performance, cost, and availability.
=> New tool - Metric Analyzer

migration/couchbase-migration-utility/README.md, migration/couchbase-migration-utility/couchbase-to-amazon-documentdb.yaml
*Issue #, if available:* n/a
*Description of changes:* Updated links to script files on main branch and fixed code blocks in README.md.
=> Couchbase migration - 2nd PR

compat-tool/README.md
Corrected instructions for Atlas
=> corrected instructions for Atlas
